In [1]:
import numpy as np
import pandas as pd

### Sample dataframe of marks

In [ ]:
marks = pd.DataFrame([
    [100,80,10],
    [90,70,7],
    [120,100,14],
    [80,70,14],
    [80,70,14]
],columns=['iq','marks','package'])

marks

    iq  marks  package
0  100     80       10
1   90     70        7
2  120    100       14
3   80     70       14
4   80     70       14

### Sample series of marks

In [ ]:
marks_dict = {
    'maths':67,
    'english':57,
    'science':89,
    'hindi':100
}

marks_series = pd.Series(marks_dict)
marks_series

maths       67
english     57
science     89
hindi      100
dtype: int64

### Sample dataframe of students

In [ ]:
students = pd.DataFrame(
    {
        'name':['nitish','ankit','rupesh',np.nan,'mrityunjay',np.nan,'rishabh',np.nan,'aditya',np.nan],
        'college':['bit','iit','vit',np.nan,np.nan,'vlsi','ssit',np.nan,np.nan,'git'],
        'branch':['eee','it','cse',np.nan,'me','ce','civ','cse','bio',np.nan],
        'cgpa':[6.66,8.25,6.41,np.nan,5.6,9.0,7.4,10,7.4,np.nan],
        'package':[4,5,6,np.nan,6,7,8,9,np.nan,np.nan]

    }
)

students

         name college branch   cgpa  package
0      nitish     bit    eee   6.66      4.0
1       ankit     iit     it   8.25      5.0
2      rupesh     vit    cse   6.41      6.0
3         NaN     NaN    NaN    NaN      NaN
4  mrityunjay     NaN     me   5.60      6.0
5         NaN    vlsi     ce   9.00      7.0
6     rishabh    ssit    civ   7.40      8.0
7         NaN     NaN    cse  10.00      9.0
8      aditya     NaN    bio   7.40      NaN
9         NaN     git    NaN    NaN      NaN

### Sample dataframe of batsman

In [ ]:
batsman = pd.read_csv('../04CampusX_DataSet/datasets-session-17/batsman_runs_ipl.csv')
batsman.head()

           batter  batsman_run
0  A Ashish Reddy          280
1        A Badoni          161
2      A Chandila            4
3        A Chopra           53
4     A Choudhary           25

### Sample Data of movies

In [ ]:
movies = pd.read_csv('../04CampusX_DataSet/datasets-session-17/movies.csv')
movies.head()

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

# **1. value_counts**

In [ ]:
# 1.1. On a temp series
temp = pd.Series([1,1,2,2,2,3,3,3,3,4,4,4,4,4])
temp.value_counts()

# 1.2. On a series within DataFrame
marks['marks'].value_counts()

# 1.3. On the DataFrame itself
marks.value_counts()

iq   marks  package
80   70     14         2
90   70     7          1
100  80     10         1
120  100    14         1
Name: count, dtype: int64

# **2. sort_values**

In [ ]:
# 2.1 
temp.sort_values() # default is ascending

# 2.2
marks["iq"].sort_values(ascending=False) # sorts the series iq 

# 2.3
students.sort_values(by='cgpa', ascending=False) # by takes column as input, and sorts df on that col

# 2.4 
students.sort_values(by='cgpa', na_position='last', ascending=False)# na default is also last
students.sort_values(by="cgpa", na_position="first", ascending=False)# keeps na at starting, sorts the values in descending order

# 2.5 Sorting the dataframe on multiple columns
students.sort_values(['name', 'branch'], ascending=[True, False], na_position='last') # na_position is only applied on name

# 2.6 Permanent changes ## Using inplace ## By re-assigning
# 2.6.1 Using inplace to make permanent changes to the dataframe
# students.sort_values('name',na_position='first',ascending=True,inplace=True)
# 2.6.2 Re-assigning the sorted dataframe to the same variable ## More prefered way
# students = students.sort_values('name',na_position='first',ascending=True) # this will make permanent changes to the dataframe

3           NaN
5           NaN
7           NaN
9           NaN
8        aditya
1         ankit
4    mrityunjay
0        nitish
6       rishabh
2        rupesh
Name: name, dtype: object

# **3. Rank**
- Creates a series assigning ranks to the batsman runs in descending order
- each index of the series corresponds to the index of the batsman in the dataframe
- ranks are calculated based on the batsman_run column of the dataframe
- since ascending=False, rank 1 ---> highest run and so on
- two batsman with same runs will get the same rank and the next rank will be skipped
- for example, if two batsman have the highest run of 100, they will both get rank 1 and the next rank will be 3
- its same as rank in sql

In [47]:
mask = batsman['batsman_run'].rank(ascending=False) # Ranks highest scrores 1

batsman['batsman_rank'] = mask # makes a new column since one already dosent exists

batsman.sort_values(by='batsman_rank').head()

        batter  batsman_run  batsman_rank
569    V Kohli         6634           1.0
462   S Dhawan         6244           2.0
130  DA Warner         5883           3.0
430  RG Sharma         5881           4.0
493   SK Raina         5536           5.0

# **4. sort_index()**
- On series & dataframe

In [ ]:
# 4.1 On Series
marks_series.sort_index(ascending=False)

# 4.2 On DataFrame
movies.sort_index(ascending=True)

# 4.3 Permanent Changes
    # 4.3.1 inplace parameter
# movies.sort_index(ascending=True, inplace=True)
    # 4.3.2 reassigning
# movies = movies.sort_index(ascending=True)